controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_homepage:
    path: /{_locale}/
    controller: App\Controller\HomeController::index
    defaults: { _locale: 'fr' }
    requirements:
        _locale: fr|en
